[package]
name = "aria-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[build-dependencies]
tauri-build.workspace = true

[dependencies]
anyhow.workspace = true
aria-core = { path = "../../../crates/aria-core" }
aria-ipc = { path = "../../../crates/aria-ipc" }
aria-model = { path = "../../../crates/aria-model" }
serde.workspace = true
tauri.workspace = true
tracing.workspace = true
